name: Integration Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9.18', '3.10.13', '3.11.5' ]

    env:
      POETRY_NO_INTERACTION: 1
      PIP_DEFAULT_TIMEOUT: 100  

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '1.6.1'
          virtualenvs-create: false
          virtualenvs-in-project: false

      - name: Install project
        run: poetry install --no-root

      - name: Execute Pytest
        run: poetry run python -m pytest tests/integration
