name: Unit Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - uses: actions/checkout@v3

      - name: Create the docker container
        run: docker compose up -d

      - name: Execute Pytest
        run: docker exec app sh -c "pytest --cov=pyyaml_object --cov-report=xml /tests/integration"